/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ibang;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.*;
import java.awt.*;
import java.lang.*;
import java.awt.event.*;
import java.io.*;
/**
 *
 * @author delilah
 */
public class Ticket_5 extends javax.swing.JFrame {

    /**
     * Creates new form Ticket_5
     */
    String name_F; String id_F; Start  ss;
    int i,j;
    int site[][]=new int[3][4];
    int temp[][]=new int[3][4];//暫時存放使用者選了哪假個位子
    int state[][]=new int[3][4];//紀錄每個按鈕的狀態
    int count_VVIP=0,count_VIP=0,count_normal=0;
    int seat_count[][]=new int [3][3];
    int str_count=0;//判斷若12個表此票沒座位了
    int a;//看目前買的是哪個演唱會的票
    public Ticket_5() {
    }
     public Ticket_5(String name,String id) {
        initComponents();
        name_F=name;
        id_F=id;
        setBak(); //調用背景方法
        Container c = getContentPane(); //獲取JFrame面板
        JPanel jp = new JPanel(); //創建個JPanel
        jp.setOpaque(false); //把JPanel設置為透明 這樣就不會遮住後面的背景 這樣你就能在JPanel隨意加元件了
        c.add(jp);       
        setSize(618, 765);
        setVisible(true);
        
        Read_concert();//讀取票張數
        int str ;
        i=0;j=0;
        BufferedReader reader = null;       
        try {
                if(name_F=="R3HAB_live_Asia_tour_2016_台北")
                {
                    reader = new BufferedReader(new InputStreamReader(new FileInputStream("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\concert_site_1.txt"), "UTF-8"));
                    a=0;
                }
                else if(name_F=="2016懷念金曲演唱會~鑽石亮晶晶林沖演唱會")
                {
                     reader = new BufferedReader(new InputStreamReader(new FileInputStream("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\concert_site_2.txt"), "UTF-8"));
                     a=1;
                }
                else if(name_F=="范瑋琪〔范范的感恩節〕音樂會")
                {
                     reader = new BufferedReader(new InputStreamReader(new FileInputStream("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\concert_site_3.txt"), "UTF-8"));
                     a=2;
                }
                while (i<3) 
                {
                    if(j<4)
                    {
                        str = reader.read()-48;//好奇怪 不知為何 0 他讀取的是48
                        if(str>=0)
                        {
                             Set_start_color(i,j,str);
                             site[i][j]=str;
                             temp[i][j]=str;
                             j++;
                        }
                    }
                    else {
                        i++;
                        j=0;
                    }
                }
                if(str_count==12)//沒位置了
                {
                    JOptionPane.showMessageDialog(null, "都沒位置囉!請回主畫面", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
                    ss= new Start();//新增視窗
                    ss.setBounds(0, 0,this.getWidth(), this.getHeight());
                    this.add(ss);
                    ss.setVisible(true);//顯現
                }
        }catch (FileNotFoundException e) 
        {
                e.printStackTrace();
        }
        catch (IOException e) 
        {
                e.printStackTrace();
        }
         finally {
                try {
                        reader.close();
                }
                catch (IOException e) {
                        e.printStackTrace();
                }
        }
     }
       public void setBak(){
            ((JPanel)this.getContentPane()).setOpaque(false);
            ImageIcon img = new ImageIcon("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\流程背景.png");
            JLabel background = new JLabel(img);
            this.getLayeredPane().add(background, new Integer(Integer.MIN_VALUE));
            background.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 51));
        jButton4.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 51));
        jButton5.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 51));
        jButton6.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 51));
        jButton7.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 51));
        jButton8.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 51));
        jButton9.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 51));
        jButton10.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton10.setText("10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 51));
        jButton11.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton11.setText("11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 51));
        jButton12.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jButton12.setText("12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\VVIP.png")); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\VIP.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\一般.png")); // NOI18N

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\確認.png")); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(37, 37, 37))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(site[0][0]==1)//已經有人選過了
        {
          JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[0][0]==0)
            {
                state[0][0]=1;
                jButton1.setBackground(Color.red);
                temp[0][0]=1;
                count_VVIP++;
            }
            else if(state[0][0]==1)
            {
                state[0][0]=0;
                jButton1.setBackground(Color.YELLOW);
                temp[0][0]=0;
                count_VVIP--;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(site[0][1]==1)//已經有人選過了
        {
          JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
           if(state[0][1]==0)
           {
               state[0][1]=1;
               jButton2.setBackground(Color.red);
               temp[0][1]=1;
                count_VVIP++;
           }
           else if(state[0][1]==1)
           {
               state[0][1]=0;
               jButton2.setBackground(Color.YELLOW);
               temp[0][1]=0;
               count_VVIP--;
           }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(site[0][2]==1)//已經有人選過了
        {
          JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[0][2]==0)
           {
               state[0][2]=1;
               jButton3.setBackground(Color.red);
               temp[0][2]=1;
                count_VVIP++;
           }
           else if(state[0][2]==1)
           {
               state[0][2]=0;
               jButton3.setBackground(Color.YELLOW);
               temp[0][2]=0;
                count_VVIP--;
           }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        Write_in();//演唱會選位位置
        Write_concert();//改變演唱會目前票剩多少
        Write_buy_people();//購買成功的寫入檔案 觀看目前成功人數為何
        JOptionPane.showMessageDialog(null, "訂票成功~~~~~", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        ss= new Start();//新增視窗
        ss.setBounds(0, 0,this.getWidth(), this.getHeight());
        this.add(ss);
        ss.setVisible(true);//顯現
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if(site[0][3]==1)//已經有人選過了
        {
          JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[0][3]==0)
            {
                state[0][3]=1;
                jButton4.setBackground(Color.red);
                temp[0][3]=1;
                count_VVIP++;
            }
            else if(state[0][3]==1)
            {
                state[0][3]=0;
                jButton4.setBackground(Color.YELLOW);
                temp[0][3]=0;
                count_VVIP--;
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(site[1][0]==1)//已經有人選過了
        {
          JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[1][0]==0)
            {
                state[1][0]=1;
                jButton5.setBackground(Color.red);
                 temp[1][0]=1;
                count_VIP++;
            }
            else if(state[1][0]==1)
            {
                state[1][0]=0;
                jButton5.setBackground(Color.YELLOW);
                temp[1][0]=0;
                count_VIP--;
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         if(site[1][2]==1)//已經有人選過了
        {
            JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[1][2]==0)
            {
                state[1][2]=1;
                jButton7.setBackground(Color.red);
                temp[1][2]=1;
                count_VIP++;
            }
            else if(state[1][2]==1)
            {
                state[1][2]=0;
                jButton7.setBackground(Color.YELLOW);
                temp[1][2]=0;
                count_VIP--;
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         if(site[1][3]==1)//已經有人選過了
        {
            JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[1][3]==0)
            {
                state[1][3]=1;
                jButton8.setBackground(Color.red);
                temp[1][3]=1;
                count_VIP++;
            }
            else if(state[1][3]==1)
            {
                state[1][3]=0;
                jButton8.setBackground(Color.YELLOW);
                temp[1][3]=0;
                count_VIP--;
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(site[1][1]==1)//已經有人選過了
        {
            JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[1][1]==0)
            {
                state[1][1]=1;
                jButton6.setBackground(Color.red);
                temp[1][1]=1;
                count_VIP++;
            }
            else if(state[1][1]==1)
            {
                state[1][1]=0;
                jButton6.setBackground(Color.YELLOW);
                temp[1][1]=0;
                count_VIP--;
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         if(site[2][0]==1)//已經有人選過了
        {
            JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[2][0]==0)
            {
                state[2][0]=1;
                jButton9.setBackground(Color.red);
                temp[2][0]=1;
                count_normal++;
            }
            else if(state[2][0]==1)
            {
                state[2][0]=0;
                jButton9.setBackground(Color.YELLOW);
                temp[2][0]=0;
                count_normal--;
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(site[2][1]==1)//已經有人選過了
        {
            JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[2][1]==0)
            {
                state[2][1]=1;
                jButton10.setBackground(Color.red);
                temp[2][1]=1;
                count_normal++;
            }
            else if(state[2][1]==1)
            {
                state[2][1]=0;
                jButton10.setBackground(Color.YELLOW);
                temp[2][1]=0;
                count_normal--;
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if(site[2][2]==1)//已經有人選過了
        {
            JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[2][2]==0)
            {
                state[2][2]=1;
                jButton11.setBackground(Color.red);
                temp[2][2]=1;
                count_normal++;
            }
            else if(state[2][2]==1)
            {
                state[2][2]=0;
                jButton11.setBackground(Color.YELLOW);
                temp[2][2]=0;
                count_normal--;
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(site[2][3]==1)//已經有人選過了
        {
            JOptionPane.showMessageDialog(null, "已經有人選過囉~請選別的座位", "IBang購票", JOptionPane.INFORMATION_MESSAGE );
        }
        else
        {
            if(state[2][3]==0)
            {
                state[2][3]=1;
                jButton12.setBackground(Color.red);
                temp[2][3]=1;
                count_normal++;
            }
            else if(state[2][3]==1)
            {
                state[2][3]=0;
                jButton12.setBackground(Color.YELLOW);
                temp[2][3]=0;
                count_normal--;
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    public void Write_in()
    {
        BufferedWriter writer=null;
        i=0;j=0;
        try {
            
                if(name_F=="R3HAB_live_Asia_tour_2016_台北")
                    writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream ("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\concert_site_1.txt"), "UTF-8"));
                else if(name_F=="2016懷念金曲演唱會~鑽石亮晶晶林沖演唱會")
                   writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream ("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\concert_site_2.txt"), "UTF-8"));
                else if(name_F=="范瑋琪〔范范的感恩節〕音樂會")
                     writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream ("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\concert_site_3.txt"), "UTF-8"));
                while(i<3)
                {
                    if(j<4)
                    {
                        writer.write(temp[i][j]+" ");
                        j++;
                    }
                    else 
                    {
                        writer.newLine();
                        i++;
                        j=0;
                    }
                }
                writer.flush();
        }catch (FileNotFoundException e) 
        {
                e.printStackTrace();
        }
        catch (IOException e) 
        {
                e.printStackTrace();
        }
         finally {
                try {
                        writer.close();
                }
                catch (IOException e) {
                        e.printStackTrace();
                }
        }
    }
    /**
     * @param args the command line arguments
     */
    
    public void Read_concert()
    {
        int str;
        BufferedReader reader = null;  
        i=0;j=0;
        try {
                
                reader = new BufferedReader(new InputStreamReader(new FileInputStream("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\concert_inform.txt"), "UTF-8"));
                
                while (i<3) 
                {
                    if(j<3)
                    {
                        str = reader.read()-48;//好奇怪 不知為何 0 他讀取的是48
                        if(str>=0)
                        {
                             seat_count[i][j]=str;
                             j++;
                        }
                    }
                    else {
                        i++;
                        j=0;
                    }
                }
        }catch (FileNotFoundException e) 
        {
                e.printStackTrace();
        }
        catch (IOException e) 
        {
                e.printStackTrace();
        }
         finally {
                try {
                        reader.close();
                }
                catch (IOException e) {
                        e.printStackTrace();
                }
        }
    }
     public void Write_concert()
     {
         int k1=seat_count[a][0],k2=seat_count[a][1],k3=seat_count[a][2];
         seat_count[a][0]=k1-count_VVIP;
         seat_count[a][1]=k2-count_VIP;
         seat_count[a][2]=k3-count_normal;
         i=0; j=0;
         //改完此演唱會的票數後 進行 改寫檔案
         BufferedWriter writer=null;
        try {
              writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream ("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\concert_inform.txt"), "UTF-8"));
                while(i<3)
                {
                    if(j<3)
                    {
                        writer.write(seat_count[i][j]+" ");
                        j++;
                    }
                    else 
                    {
                        writer.newLine();
                        i++;
                        j=0;
                    }
                }
                writer.flush();
        }catch (FileNotFoundException e) 
        {
                e.printStackTrace();
        }
        catch (IOException e) 
        {
                e.printStackTrace();
        }
         finally {
                try {
                        writer.close();
                }
                catch (IOException e) {
                        e.printStackTrace();
                }
        }
     }
     public void Set_start_color(int i,int j,int str)
     {
         if(i==0&&j==0)
         {
             if(str==1)
             {
                 jButton1.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton1.setBackground(Color.YELLOW);
         }
         else  if(i==0&&j==1)
         {
             if(str==1)
             {
                 jButton2.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton2.setBackground(Color.YELLOW);
         }
         else  if(i==0&&j==2)
         {
             if(str==1)
             {
                 jButton3.setBackground(Color.red);
                str_count++; 
             }  
             else if(str==0)
                 jButton3.setBackground(Color.YELLOW);
         }
         else  if(i==0&&j==3)
         {
             if(str==1)
             {
                 jButton4.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton4.setBackground(Color.YELLOW);
         }
         else  if(i==1&&j==0)
         {
             if(str==1)
             {
                 jButton5.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton5.setBackground(Color.YELLOW);
         }
         else  if(i==1&&j==1)
         {
             if(str==1)
             {
                 jButton6.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton6.setBackground(Color.YELLOW);
         }
         else  if(i==1&&j==2)
         {
             if(str==1)
             {
                 jButton7.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton7.setBackground(Color.YELLOW);
         }
         else  if(i==1&&j==3)
         {
             if(str==1)
             {
                 jButton8.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton8.setBackground(Color.YELLOW);
         }
         else  if(i==2&&j==0)
         {
             if(str==1)
             {
                 jButton9.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton9.setBackground(Color.YELLOW);
         }
          else  if(i==2&&j==1)
         {
             if(str==1)
             {
                 jButton10.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton10.setBackground(Color.YELLOW);
         }
          else  if(i==2&&j==2)
         {
             if(str==1)
             {
                 jButton11.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton11.setBackground(Color.YELLOW);
         }
          else  if(i==2&&j==3)
         {
             if(str==1)
             {
                 jButton12.setBackground(Color.red);
                 str_count++;
             }
             else if(str==0)
                 jButton12.setBackground(Color.YELLOW);
         }
     }
     public void Write_buy_people()
     {
        BufferedReader reader = null;  
        String s1;
        String people[] =new String[100];int k=0;
        int money;
        money=count_VVIP*100+count_VIP*50+count_normal*20;
        i=0;j=0;
        BufferedWriter writer=null;
        try {
              reader = new BufferedReader(new InputStreamReader(new FileInputStream("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\concert_buy.txt"), "UTF-8"));
              while((s1=reader.readLine())!=null)
              {
                  people[k]=s1;
                  k++;
              }
              people[k]=id_F+" "+name_F+"\t"+count_VVIP+"\t"+count_VIP+"\t"+count_normal+"\t"+money;
              k++;
              writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream ("C:\\Users\\delilah\\Desktop\\JAVA期末專題\\ibang\\concert_buy.txt"), "UTF-8"));
                while(i<k)
                {
                    writer.write(people[i]);
                    writer.newLine();
                    i++;
                }
                writer.flush();
        }catch (FileNotFoundException e) 
        {
                e.printStackTrace();
        }
        catch (IOException e) 
        {
                e.printStackTrace();
        }
         finally {
                try {
                      reader.close();
                        writer.close();
                }
                catch (IOException e) {
                        e.printStackTrace();
                }
        }
     }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket_5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
